---
title: "C# for BIM 강좌"
date: 2020-07-22 22:00:00 -0400
categories: BIM
toc: true
toc_sticky: true
---

Udemy - Learn to program the Revit API by Boost Your BIM

## Section 1-9. External Command 생성과 Revit Add-In으로 적용하는 방법

1. 아래와 같이 VS(Visual Studio)를 이용하여 코드를 입력하고 빌드한다.

```c#
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace [ProjectName]
{
    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.ReadOnly)]
    public class [ClassName] : IExternalCommand
    {
        static AddInId appId = new AddInId(new Guid("[GUID, 예: E4A27922-E4EC-48F4-A39E-4E1232D5319D]")); // Guid = Globally unique id, VS의 Tools->Create Guid->5번 포맷으로 생성
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)
        {
            [기능에 대한 코드]
        }
    }
}
```

2. Visual Studio 안에서 만든 [ClassName].cs 탭 클릭 -> Open Containing Folder -> bin/debug/ 안의 [ProjectName].dll 파일을 찾는다.
  * [ProjectName].dll은 Visual Studio 안에서 만든 매크로이며, External Command로 쓰일 파일이다.
  * 파일의 경로 예) C:\Users\[UserName]\source\repos\[ProjectName]\[ProjectName]\bin\Debug\netstandard2.0\[ProjectName].dll
  
3. C:\ProgramData\Autodesk\Revit\Addins\[Years]에 [Any File Name].addin을 생성한다. 안의 코드 내용은 아래와 같다.

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<RevitAddIns>
	<AddIn Type="Command">
		<Assembly>C:\Users\[UserName]\source\repos\[ProjectName]\[ProjectName]\bin\Debug\netstandard2.0\[ProjectName].dll</Assembly>
		<AddInId>[GUID]</AddInId>
		<FullClassName>[ProjectName].[ClassName]</FullClassName>
		<Text>[Revit Add-in 탭의 External Tools에 표시될 설명]</Text>
		<VendorId>BYBM</VendorId> // Commercial Developement시 필요한 ID
	</AddIn>
</RevitAddIns>	
```

4. Revit을 실행 후, Add-Ins 탭의 External Tools 메뉴에 있는 Add-In을 실행해본다. 끝..

## Section 1-10. 코드를 통해 Revit 모델을 변경하는 방법: Transaction class를 통하여

아래의 코드는 새로운 Family Type 및 Parameter와 Parameter value를 input하는 코드이다.

```c#
public void FamilyTypesParameters()
{
  Document doc = this.ActiveUIDocument.Document;
  if (!doc.IsFamilyDocument) // Revit에서 현재 활성화되어 있는 document가 FamilyDocument가 아니라면 아래 코드를 실행하지 않고 return한다.
  {
    return;
  }

  using (Transaction t = new Transaction(doc, "family test")) // Transaction(document, "transaction name")
  {
    t.Start(); // Transaction 시작
    
    [Revit Model을 변경하는 코드]
    
    t.Commit(); // Transaction 종료
  }
}
```

아래의 코드는 예제코드와 설명이다.

```c#
public void FamilyTypesParameters()
{
  Document doc = this.ActiveUIDocument.Document;
  if (!doc.IsFamilyDocument) // Revit에서 현재 활성화되어 있는 document가 FamilyDocument가 아니라면 아래 코드를 실행하지 않고 return한다.
  {
    return;
  }
  /*
  *코드를 통해 모델을 변경할 때마다 Transation class을 사용해야한다. 
  *변경이 진행되는 동안 다른 변경이 발생하지 않도록 Transaction은 모델을 잠근다. 
  *Transaction 코드는 매우 간단하다. 
  *'모델을 변경하는 코드'를 감싸고 있다
  *Transaction 코드 없이 매크로를 실행하려하면 오류가 발생한다. 
  */
  using (Transaction t = new Transaction(doc, "family test")) // Transaction(document, "transaction name")
  {
    t.Start(); // Transaction 시작
    FamilyManager mgr = doc.FamilyManager; // Family type과 parameter를 관리할 수 있는 FamilyManager를 변수로 저장.

    FamilyParameter param = mgr.AddParameter("New Parameter", BuiltInParameterGroup.PG_DATA, ParameterType.Text, false); // FamilyParameter Object로서의 param 변수 = ("Parameter Name", Parameter_group, Parameter_Type, bool(instace or type?))

    for (int i = 1; i < 5; i++) // i = 1 to 4 까지 
    {
      FamilyType newType = mgr.NewType(i.ToString()); // for문에 의한 i값(1,2,3,4)를 새로운 familytype으로 추가한다.
      mgr.CurrentType = newType; // CurrentType의 family type만이 FamilyManager 안에서 편집될 수 있기에 current type으로 바꿔준다.
      mgr.Set(param, "this value " + i); // parameter의 value를 세팅할 때 쓰인다. Set(FamilyParameter, Value)
    }

    t.Commit(); // Transaction 종료
  }
}
```

## Section 1-11. Line의 Length를 구하는 법과, 단위를 Convert하는 방법

## Section 2-12. Text Files를 읽고 쓰는 방법

아래는 text file을 작성하는 함수이다.

```c#
public void WriteTextFile()
{
  string filename = @"C:\Users\Minguk Kim\Desktop\test.txt";
  
  if (File.Exists(filename)) //  파일이 존재한다면, 파일을 지운다.
  {
    File.Delete(filename);
  }


  // StreamWriter writer = new StreamWrite(filename, true); // 두번째 파라미터: (기존 파일이 존재한다면) true --> 그 다음 줄에 씀. false --> 파일에 덮어씌움. 

  /* 
  * using을 쓴다면 writer.close()를 할 필요가 없다. using block에서 자동으로 처리해줌. 
  */
  using (StreamWriter writer = new StreamWriter(filename))
  {
    writer.WriteLine("First Line");
    writer.WriteLine("Second Line");
  }
}
```

아래는 Text file을 읽는 함수 이다.

```c#
/*
Text file의 전체 Line을 읽는 함수
*/
public void ReadTextFileAll()
{
  string filename = @"C:\[path]\test.txt";

  string fileContents = "";
  
  using (StreamReader reader = new StreamReader(filename))
  {
    string thisLine = "";
    while (thisLine != null) // 라인에 아무 것도 없을 때(null)까지 라인을 읽는다. 
    {
      thisLine = reader.ReadLine();
      fileContents = fileContents + thisLine + "\n";
    }
    TaskDialog.Show(filename, fileContents);
  }
}
```
## Section 2-13. 경로 설정

```c#
/* 해당 경로의 폴더에 있는 .rfa 확장자를 가진 파일들의 리스트를 보여주는 함수 */
public void AllFilesInFolder()
{
  string files = "";
  string folder = @"C:\ProgramData\Autodesk\RVT 2018\Libraries\US Imperial\Structural Framing\Steel";
  foreach (string filename in Directory.GetFiles(folder, "*.rfa")) // folder 경로의 .rfa 확장자를 가진 각각의 filename들을 추가시키는 files 변수에 추가시키는 함수
  {
    files += filename + Environment.NewLine;
  }
  TaskDialog.Show("files", files);
}
```

## Section 2-14. Revit API external command로 엑셀(*.xslx) 읽기
## Section 2-15. Excel로 Revit data 작성하기
Section 2-14와 2-15 [EPPlus](https://archive.codeplex.com/?p=epplus)를 이용해야하지만, 유료이므로 넘어가봄..추후 다른 방법 찾기

## Section 2-16. Exception Handling
This section shows how to handle exceptions that are thrown during the execution of Revit API code
Exception = error임.
Trhow an exception = error가 발생했을 때, 서술형으로 error에 대하여 설명하는 것.

아래 코드는 오브젝트를 Pick하는 함수이다. 여기서 esc키를 누르면 에러가 발생한다.

```c#
public void SelectionException()
{
  UIDocument uidoc = this.ActiveUIDocument;
  Document doc = uidoc.Document;
  uidoc.Selection.PickObject(ObjectType.Element);
}
```

아래의 코드는 esc키를 눌렀을 때, 위의 코드처럼 장황한 에러메세지가 나오는 것 대신에 원하는 메세지를 출력하게 할 수 있다.
아래와 같이 try-catch block을 만든다면, try 안의 code를 실행시키는데 exception이 발생되면, 그것을 catch 하여 catch 안의 코드를 실행시키는 것을 볼 수 있다.

```c#
public void SelectionException()
{
  UIDocument uidoc = this.ActiveUIDocument;
  Document doc = uidoc.Document;

  try 
  {
    uidoc.Selection.PickObject(ObjectType.Element);	
  } 

  catch (Exception)
  {
    TaskDialog.Show("Error", "User aborted");
    // 만약에 return;을 한다면 아무것도 내보내지 않음.
  }

}
```

만약 각각의 Exception에 대하여 Throw를 하고 싶다면, 아래와 같이 catch를 병렬로 구성할 수 도 있다.

```c#
try 
{
  myRef = uidoc.Selection.PickObject(ObjectType.Element);	
} 
catch (Autodesk.Revit.Exceptions.OperationCanceledException)
{
  return;
}
catch (Autodesk.Revit.Exceptions.ArgumentOutOfRangeException)
{
  return;
}
```

## Section 2-17. Code Reuse and Helper Functions

하드코딩 대신에 function을 만들어서 이를 다른 function 쓸 때 이용하는 방식을 알려주는 섹션.
굳이 볼 필요는 없을 듯

```c#
/*
  * 호스트오브젝트와 레퍼런스리스트를 input으로 받고,
  * foreach문에서 레퍼런스 리스트를 반복하여 string에 각 face의 면적을 입력하는 함수. 
  * */
private string getFaceInfo(HostObject ho, IList<Reference> refList)
{
  string s = "";
  foreach (Reference r in refList)
  {
    Face f = ho.GetGeometryObjectFromReference(r) as Face;
    s += "Face area = " + Math.Round(f.Area) + ", " + Environment.NewLine;
    s += "Edge length = ";
    foreach (EdgeArray ea in f.EdgeLoops)
    {
      foreach (Edge e in ea)
      {
        s += Math.Round(e.ApproximateLength,2) + ", ";
      }
    }
    s += Environment.NewLine;
  }
  return s;
}

public void HostFaces()
{
  Document doc = this.ActiveUIDocument.Document;
  string info = "";
  foreach (HostObject hostObj in new FilteredElementCollector(doc).OfClass(typeof(HostObject)))
  {
    info += hostObj.Name + Environment.NewLine;
    try
    {
      info += getFaceInfo(hostObj, HostObjectUtils.GetSideFaces(hostObj, ShellLayerType.Exterior));
    }
    catch (Autodesk.Revit.Exceptions.ArgumentException)
    {}

    try
    {
      info += getFaceInfo(hostObj, HostObjectUtils.GetTopFaces(hostObj));
    }
    catch (Autodesk.Revit.Exceptions.ArgumentException)
    {}

    try
    {
      info += getFaceInfo(hostObj, HostObjectUtils.GetBottomFaces(hostObj));
    }
    catch (Autodesk.Revit.Exceptions.ArgumentException)
    {}

    info += Environment.NewLine + Environment.NewLine;
  }
  TaskDialog.Show("Host Objects", info);
}
```

## Section 2-18. Obsolete Members의 의미

Obsolete는 "일반적으로 쓰이고 있지 않은"이라는 뜻을 지니고 있다. Obsolete Attribute는 함수에 사용되며, 해당 함수를 사용할 경우 컴파일 시, 경고를 발생시킨다.
예) Element와 ElementId 중 ElementId를 사용한다. 왜냐하면 ElementId가 훨씬 smaller, lighter 하기 때문이다. 따라서 Element는 일반적으로 Obsolete Attribute로 분류되기에, 굳이 Element를 쓰지 않는다.

## Section 2-19. User Input을 위한 Windows Form 생성 방법

Windows Form 세팅방법은 강좌 동영상을 참고할 것. 해당 포스트에서는 생략했음.
* Windows Form에서 OK, Cancel 버튼을 만들었다면 Properties에서 AcceptButton과 CancelButton 밸류를 해당 버튼으로 줘야함.
```myNewForm.cs```는 Windows Form에서 정보를 받고 함수를 통해 가공하는 역할
```Class1.cs```을 통해 애드인을 실행한다. 

아래 코드에 대한 설명:
Revit 상에서 MoveObject라는 애드인을 실행 -> Object를 Pick함 -> Windows Form이 뜨면 움직일 축의 방향, 거리를 입력하고 OK -> 오브젝트가 움직임.

아래는 Class Library인 ```클래스명: Class1.cs```의 코드이다. 

```c#
using Autodesk.Revit.DB; // 얘네를 필히 Import 해야함.
using Autodesk.Revit.UI; // 얘네를 필히 Import 해야함.
using Autodesk.Revit.UI.Selection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BoostMyBIMAPI // addin 파일의 [ProejctName]과 동일해야함. // addin 경로: C:\ProgramData\Autodesk\Revit\Addins\2018
{
    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)] // ReadOnly는 Revit Model를 변경하지 못한다. Manual로 해야 변경이 될 수 있음.
    public class MoveObject : IExternalCommand // addin 파일의 [className]과 동일해야함. // addin 경로: C:\ProgramData\Autodesk\Revit\Addins\2018
    {
        static AddInId appId = new AddInId(new Guid("BB4267C3-E978-401A-8D4E-144A8FB306D6"));
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)
        {
            UIDocument uidoc = commandData.Application.ActiveUIDocument;
            Document doc = uidoc.Document;
            Element e = doc.GetElement(uidoc.Selection.PickObject(ObjectType.Element)); // 유저가 Element를 Pick하게 한다.

            /* initialize these[distance, isHoriz] variables*/
            double distance = 0; 
            bool isHoriz = false;

            // 유저가 Element를 Pick하면, Dialog Box(아까 만든 Windows Form)을 뜨게한다.
            using (myNewForm thisForm = new myNewForm())
            {
                thisForm.ShowDialog();
                if (thisForm.DialogResult == System.Windows.Forms.DialogResult.Cancel) // Form이 캔슬된다면 아래 코드를 실행
                {
                    return Result.Cancelled;
                }
                // 위 if statement에서 Cancel되지 않았다면 Form의 Input 창에서 정보를 get해서 document를 수정할 것임.
                // 아래 2줄의 코드는 Windows form에 작성된 input으로부터 distance와 isHorizontal values를 받는 것.
                distance = thisForm.getDistance();
                isHoriz = thisForm.isHorizontal();
            }

            XYZ moveVector = null;
            if (isHoriz) // Windows Form에서 Horizontal이 선택되었으면, X좌표가 이동될 것임.
                moveVector = XYZ.BasisX.Multiply(distance); // 예)--> Distance=5 이면, BasisX*Distance = (1,0,0)*5 = (5,0,0) 만큼 이동
            else
                moveVector = XYZ.BasisY.Multiply(distance);


            // 위의 코드들에서 받은 information들을 가지고 object를 이동시킬 것임.
            using (Transaction t = new Transaction(doc, "Move Object")) // (다큐먼트, 트랜잭션 이름)
            {
                t.Start();
                ElementTransformUtils.MoveElement(doc, e.Id, moveVector); // (다큐먼트, 엘리먼트아이디, 얼마나움직일건지)
                t.Commit();
            }


            return Result.Succeeded;
        }
    }
}

```

아래는 Windows Form Class인 ```클래스명: myNewForm.cs```의 코드이다.

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BoostMyBIMAPI
{
    public partial class myNewForm : Form
    {
        public myNewForm()
        {
            InitializeComponent();
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.OK;
            Close();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        /*
         Vertical인지 Horizontal인지에 따라 boolean값을 return하는 함수
         */
        public bool isHorizontal()
        {
            if (rdoHorizontal.Checked) // Horizontal button이 체크되면 true를 return.
                return true;
            else // Vertical button이 체크되면 false를 reeturn.
                return false;
        }

        /*
         유저가 textbox로부터 distance를 입력받는 함수
        textbox에서 받은 string type의 value를 double type으로 전환시킴.
         */
        public double getDistance()
        {
            double d;
            Double.TryParse(txtDistance.Text, out d); // 매개변수1을 받아서 double type의 매개변수2로 변환 
            return d;
        }
    }
}
```

## Section 2-19-추가. Visual Studio에서 빌드하면 자동으로 Revit이 실행되게 하는 방법

SolutionExplorer의 Project의 Properties 항목을 클릭한다 -> 왼쪽 목록 중 Build Events를 클릭한다 -> 
Post-build event command line에 아래와 같이 Revit.exe의 경로를 입력한다(경로는 다를 수도 있음. 필히 확인 할 것.)
```"C:\Program Files\Autodesk\Revit 2018\Revit.exe"```


